version: '3'

services:
  web:
    build: .
    command: >
      bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    environment:
      - DEBUG=False
      - DATABASE_HOST=db
    volumes:
      - .:/code
      - static_volume:/code/static
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:16
    env_file:
      - .env
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6

  celery:
    build: .
    command: >
      bash -c "celery -A config  worker --loglevel=info"
    env_file:
      - .env
    depends_on:
      - redis
      - db
    volumes:
      - .:/code

  celery_beat:
    build: .
    env_file:
      - .env
    command: >
      bash -c "celery -A config beat --loglevel=info"
    depends_on:
      - redis
      - db
    volumes:
      - .:/code

volumes:
  postgres_data:
  static_volume: