# Generated by Django 5.1.7 on 2025-03-21 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Место выполнения привычки",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Время, когда необходимо выполнять привычку",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Действие, которое представляет собой привычка",
                    ),
                ),
                (
                    "is_nice_habit",
                    models.BooleanField(verbose_name="Признак приятной привычки"),
                ),
                (
                    "period",
                    models.IntegerField(
                        blank=True,
                        choices=[("day", "Ежедневно"), ("week", "Еженедельно")],
                        null=True,
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "time_to_done",
                    models.TimeField(
                        blank=True,
                        null=True,
                        verbose_name="Время на выполнение (в минутах)",
                    ),
                ),
                ("is_public", models.BooleanField(verbose_name="Публичная привычка")),
                (
                    "linked_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linked_habits",
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
